### ISSUE TITLE
Links should be updated

### ISSUE THREAD

**Issue by liviuconcioiu** [williamdes/mariadb-mysql-kbs#300]
Hi @williamdes!

Some links should be updated to avoid some round trips.

For example:

https://mariadb.com/kb/en/library/documentation/columns-storage-engines-and-plugins/storage-engines/aria/aria-system-variables/#aria_stats_method became https://mariadb.com/kb/en/aria-system-variables/#aria_stats_method

https://mariadb.com/kb/en/library/documentation/xtradbinnodb-server-system-variables/#innodb_max_dirty_pages_pct became https://mariadb.com/kb/en/innodb-system-variables/#innodb_max_dirty_pages_pct

**Comment by williamdes** [comment]
Absoluetely, the code should detect 301 redirects and update them in the file

**Comment by williamdes** [comment]
https://github.com/williamdes/mariadb-mysql-kbs/releases/tag/v1.3.0
