### ISSUE TITLE
Issue in release file

### ISSUE THREAD

**Issue by ttodua** [williamdes/mariadb-mysql-kbs#94]
Hi.
In release.php, the first line (`#!/usr/bin/env php`) is not a php command:
https://github.com/williamdes/mariadb-mysql-kbs/blob/master/scripts/release.php

causing the wordpress based plugins to fail passing the validation.
Can that be removed?

**Comment by williamdes** [comment]
@ttodua yes, I can remove it
My release script is bad, I do not like it. 
Can you post a screenshot or the tool that makes validation so I can have more knowledge about it?

**Comment by ttodua** [comment]
It wordpress plugins repository. Any plugin, that includes this, fails to validate. reason was like:

... //Fatal error: strict_types declaration must be the very first statement in the script. ....

**Comment by williamdes** [comment]
Thank you @ttodua 
This will be fixed in next version of phpMyAdmin
I will release 1.2.9 soon

**Comment by ttodua** [comment]
Excellent support for your work! should be as a reference :)

**Comment by williamdes** [comment]
> Excellent support for your work! should be as a reference :)

Thank you so much !

**Comment by williamdes** [comment]
https://github.com/williamdes/mariadb-mysql-kbs/releases/tag/v1.2.9 is out :ship:
